server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///crm50?useSSL=false
    username: root
    password: wddcxx20010303.
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    port: 6379
    host: 127.0.0.1
    password: wddcxx20010303.
    timeout: 5000
    database: 0
    cache_name: zltredis
logging:
  level:
#    com.zlt.springboot2.controller: debug
    root: info
  file:
    path: D:\study\javaProject\cxl\src\stage3\springboot\sourceCode\springboot2\src\main\resources\static\logger
    name: mylog.log